name: special_pals
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: any
  card_swiper: ^3.0.1
  audioplayers: ^6.4.0
  like_button: ^2.0.5  
  avatar_glow: ^3.0.1
  after_layout: any
  rect_getter: ^1.1.0
  gradient_text_widget: ^0.0.4
  flutter_colorpicker: any
  image_picker: any
  simple_animations: any
  flutter_shapes: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/panda.png"

flutter:
  uses-material-design: true

  assets:
    - assets/redpanda.png
    - assets/panda.png
    - assets/Bevis.png
    - assets/draw.jpg
    - assets/Story.jpg
    - assets/Learn.png
    - assets/dream.jpg
    - assets/d.png
    - assets/book.jpg
    - assets/puzzle.jpg
    - assets/kids.jpg
    - assets/colorpalette.png
    - assets/Bell.mp3
    - assets/lion.mp3
    - assets/freeh.jpg
    - assets/shapes.jpg
    - assets/elephant.png
    - assets/elephant.mp3
    - assets/numbers.jpg
    - assets/match.jpg
    - assets/animal.jpg
    - assets/puzz.png
    - assets/anim.png
    - assets/fruit.png
    - assets/flowers.png
    - assets/fr1.jpg
    - assets/fr2.jpg
    - assets/fr3.jpg
    - assets/lion.png
    - assets/toucan.png
    - assets/chameleon.png
    - assets/armadillo.png
    - assets/hippo.png
    - assets/owl.png
    - assets/giraffe.png
    - assets/zebra.png
    - assets/li.jpg
    - assets/ti.jpg
    - assets/be.jpg
    - assets/ra.jpg
    - assets/ow.jpg
    - assets/s1.png
    - assets/s2.png
    - assets/s3.png
    - assets/f.png
    - assets/zebra.mp3
    - assets/Armadillo.mp3
    - assets/Hippopotamus.mp3
    - assets/Owl.mp3
    - assets/Toucan.mp3
    - assets/Giraffe.mp3
    - assets/Square.png
    - assets/Triangle.png
    - assets/Rectangle.png
    - assets/Circle.png

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
    - family: PTSans
      fonts:
        - asset: fonts/PTSans-Regular.ttf
    - family: LoveYaLikeASister
      fonts:
        - asset: fonts/LoveYaLikeASister-Regular.ttf
